# Generated by Django 3.1.5 on 2021-06-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210618_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accountcode',
            field=models.TextField(default='ZZZ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='enter bio text here'),
        ),
    ]
