# Generated by Django 3.1.5 on 2021-07-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210729_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.TextField(default='', max_length=100),
        ),
    ]
